name: RaidLimiter
main: fun.doomteam.raidlimiter.RaidLimiter
version: ${version}
api-version: 1.15
author: DoomsdaySociety
softdepend:
- PlaceholderAPI
commands:
  raidlimiter:
    descrption: main command
    aliases: [raid]