# 冷却模式
# SERVER - 默认设置，全服共用一个冷却，即一人触发掠夺，全服都不能再触发掠夺直到冷却结束
# PLAYER - 每个玩家分开冷却，即一人触发掠夺，他在冷却结束前不能触发掠夺，但其他还没冷却的玩家可以触发
mode: SERVER

# 在触发掠夺后执行的命令
# 命令全部都要加前缀，否则插件不读，前缀列表如下
# message:私信
# message-all:公告
# player:玩家执行命令
# console:控制台执行命令
# sound:音效,音量,音调
# action:快捷栏上出现的ActionBar消息
# title:标题消息
# subtitle:副标题消息
# 我懒得写，所以标题和副标题都是0.5秒淡出淡入，持续2秒
# 命令支持PAPI变量
###### 模式提示 ######
# 在模式为 SERVER 时
# 增加时间: console:raidlimiter add 时间
# 设置时间: console:raidlimiter set 时间
# 在模式为 PLAYER 时
# 增加时间: console:raidlimiter add 玩家名 时间
# 设置时间: console:raidlimiter set 玩家名 时间
# 玩家名可用PAPI变量 %player_name% 代替
# 时间格式为 年y月M日d时h分m秒s
# 不要相应参数后面的字母为不设置或者增加为0个单位
###### 设置时间的例子 ######
# 设置时间只会设置已填入的参数的值
# 不会覆盖没有填入的参数
# 原时间: 1970年1月1日08:00:00
# 填入时间: 3d9m
# 设置后时间: 1970年1月3日08:08:00
###### 增加时间的例子 ######
# 原时间: 1970年1月1日08:00:00
# 填入时间 1d
# 设置后时间: 1970年1月2日08:00:00
###### 例子:添加一天冷却时间，但是是次日六点冷却结束而不是冷却24小时 ######
# console:raidlimiter add 1d
# console:raidlimiter set 6h0m0s
###### 最后，敬请发挥你的想象力 ######
###### 避免有人不看上面那么长的帮助，在这里再提醒一遍，记得仔细看注释 ######
commands:
- 'console:raidlimiter add 2h'